datasources.default.url=jdbc:postgresql://localhost:5432/aluguel
datasources.default.username=aluguel
datasources.default.password=aluguel
datasources.default.driver-class-name=org.postgresql.Driver

jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.default.properties.hibernate.hbm2ddl.auto=update
