@startuml
left to right direction
actor Cliente
actor Agente
actor Empresa
actor Banco
Agente <|-- Empresa
Agente <|-- Banco

rectangle "Sistema de Aluguel de Carros" {
  usecase "Cadastrar usuário" as UC1
  usecase "Realizar login" as UC2
  usecase "Criar pedido de aluguel" as UC3
  usecase "Consultar pedidos" as UC4
  usecase "Modificar pedido" as UC5
  usecase "Cancelar pedido" as UC6
  usecase "Avaliar pedido" as UC7
  usecase "Registrar análise financeira" as UC8
  usecase "Aprovar/Reprovar pedido" as UC9
  usecase "Executar contrato" as UC10
  usecase "Associar contrato de crédito" as UC11
  usecase "Cadastrar/Listar automóveis" as UC12
}

Cliente --> UC1
Agente --> UC1
Cliente --> UC2
Agente --> UC2
Cliente --> UC3
Cliente --> UC4
Cliente --> UC5
Cliente --> UC6
Agente --> UC4
Agente --> UC5
Agente --> UC7
Agente --> UC8
Agente --> UC9
Agente --> UC10
Banco --> UC11
Agente --> UC12
@enduml
